### PR TITLE
Fixed shebang line and imports order

### PR DESCRIPTION
**Pull request by maduck**

### CODE REVIEW

**Review by marshki — COMMENTED** [review]
I believe that the "right way" to present `from __future__ import print_function` , etc. is with it at at the first line. For context, [see here](http://python-future.org/imports.html) .

**Comment by maduck** [comment]
m(
what happens if you call your script from the command line directly, like ```./pyWype.py```?

**Comment by marshki** [comment]
You wouldn't be able to invoke it directly; you'd have to invoke it manually. In which case I guess the shebang isn't needed?

**Comment by maduck** [comment]
exactly. Thus the first line of your script is actually the one _after_ the shebang line. That's why your `__future__` import needs to be both in the first line of your script **and** after the shebang.

**Pull request merged**
